set -e
echo "Compilando client..."
mvn compiler:compile -f "/workspaces/ejercicio7/client/pom.xml"
echo "Compilando server..."
mvn compiler:compile -f "/workspaces/ejercicio7/server/pom.xml"
echo "Creando JAR de client..."
mvn jar:jar -f "/workspaces/ejercicio7/client/pom.xml"
echo "JAR de client creado!"
echo "Creando JAR de server..."
mvn jar:jar -f "/workspaces/ejercicio7/server/pom.xml"
echo "JAR de server creado!"
echo "Copiando dependecias de los proyectos..."
mvn dependency:copy-dependencies -f "/workspaces/ejercicio7/client/pom.xml"
mvn dependency:copy-dependencies -f "/workspaces/ejercicio7/server/pom.xml"
echo "Todo listo!"